[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "backend"
version = "0.0.1"
description = ''
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "Ahmad Khidir", email = "khidirahmad05@gmail.com" },
]
dependencies = [
  "fastapi[standard]",
  "mangum",
  "aws-lambda-powertools",
  "pydantic",
  "boto3",
  "internal @ file:../internal",
]

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
  "types-boto3[full]",
]

[tool.hatch.build.targets.wheel]
packages = ["src/backend"]

[tool.hatch.metadata]
allow-direct-references = true
