name: Infrastructure Deploy
on:
  push:
    branches: [main]
    paths:
      - "infra/**"
  workflow_call:

jobs:
  infra:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3 # Updated to v3 for 2026
        with:
          terraform_version: 1.14.3
      - name: "Configure AWS credentials(OIDC)"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{ secrets.AWS_ROLE_TO_ASSUME }}"
          role-session-name: "github-actions"
          aws-region: "${{ vars.AWS_REGION }}"
      - name: "Terraform deploy"
        run: bash ${{ github.workspace }}/.github/workflows/terraform-deploy.sh
        working-directory: "infra/environments/prod"
  # This job fetches outputs needed by the backend
  backend:
    uses: ./.github/workflows/backend.yml
    needs: infra
    secrets: inherit
    permissions:
      id-token: write
      contents: read
